language: objective-c

xcode_project: Swifternalization.xcodeproj
xcode_scheme: SwifternalizationTests
osx_image: xcode6.3

script:
- xcodebuild clean build test -project Swifternalization.xcodeproj -scheme SwifternalizationTests